spm:
  - url: 
    from:
    path: 
    branch:
    exact: 
    revision:
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: ScadeKaigi2020
  id: com.scade.ScadeKaigi2020
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  export-method: ad-hoc # app-store, enterprise or development
  simulator:
    os: 12.1
    output: ScadeKaigi2020/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
  device: 
    os: 12.1
    output: ScadeKaigi2020/.build/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
  mac:
    os: 10.11
    output: ScadeKaigi2020/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: []
  sign:
    provision-profile: /Users/Hiromu.Tsuruta/XcodeApp/profile/appscade.mobileprovision
    certificate: /Users/Hiromu.Tsuruta/XcodeApp/profile/appscade.p12
  icons: 
    iphone: # or ipad, sizes: 20X20, 29X29, 40X40, 60X60, 76X76, 83.5X83.5
      60X60_2X:
      76X76_2X:
      76X76_3X:
      83.5X83.5_2X:
    marketing:
      1024X1024_1X:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: ScadeKaigi2020
  id: com.scade.ScadeKaigi2020
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties:
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: ScadeKaigi2020/.build/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: []
  arm64-v8a:
    output: ScadeKaigi2020/.build/android-arm64-v8a
    extra-args:
    search-paths: []
    linked-libs: []
  x86:
    output: ScadeKaigi2020/.build/android-x86
    extra-args:
    search-paths: []
    linked-libs: []
  x86_64:
    output: ScadeKaigi2020/.build/android-x86_64
    extra-args:
    search-paths: []
    linked-libs: []
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi:
    hdpi:
    xhdpi: 
    xxhdpi:
